#!/usr/bin/env python
from __future__ import print_function
import sys
import rospy
import actionlib

from mdr_move_base_action.msg import MoveBaseAction, MoveBaseGoal

if __name__ == '__main__':
    rospy.init_node('mdr_move_base_client_test')
    client = actionlib.SimpleActionClient('move_base_server', MoveBaseAction)
    client.wait_for_server()
    goal = MoveBaseGoal()
    if len(sys.argv) == 2:
        try:
            goal.goal_type = MoveBaseGoal.NAMED_TARGET
            goal.destination_location = str(sys.argv[1])
            timeout = 15.0
            rospy.loginfo('Sending action lib goal to move_base_server, ' +
                          'destination : ' + goal.destination_location)
            client.send_goal(goal)
            client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
            print(client.get_result())
        except Exception as exc:
            print(str(exc))
    else:
        rospy.logerr('Arguments were not received in the proper format')
        rospy.loginfo('usage : rosrun mdr_move_base_action move_base_client_test DESTINATION')
