#!/usr/bin/env python2

import rospy
import actionlib

from mdr_find_people.msg import FindPeopleAction, FindPeopleGoal


if __name__ == '__main__':
    rospy.init_node('find_people_client_test')

    rospy.loginfo('Waiting for server...')
    client = actionlib.SimpleActionClient('find_people_server', FindPeopleAction)
    client.wait_for_server()

    goal = FindPeopleGoal()

    try:
        print('Sending goal...')
        client.send_goal(goal)
        print('Waiting for result...')
        client.wait_for_result(rospy.Duration.from_sec(120))

        result = client.get_result()
        if result is None:
            rospy.logerr('No people found')
        rospy.loginfo('Found {0} people'.format(len(result.person_list.persons)))
        for person in result.person_list.persons:
            rospy.loginfo('Image_size: width -- {0}, height -- {1}'.format(person.rgb_image.width, person.rgb_image.height))
    except Exception as e:
        rospy.logerr('Failed to execute find people action: {}'.format(repr(e)))

