#! /usr/bin/env python3
import sys

import rospy
import roslib
import actionlib

from mdr_detec_person_action.msg import DetectPersonAction, DetectPersonGoal, DetectPersonFeedback, DetectPersonResult

if __name__ == '__main__':
    rospy.init_node('detect_person_client_test')

    client = actionlib.SimpleActionClient('detect_person_server_server', MoveTrayAction)
    client.wait_for_server()

    goal = DetectPersonGoal()
    goal.start = True
    client.send_goal(goal)
    client.wait_for_result()
    print client.get_result()

