#!/usr/bin/env python3

import rospy
import speech_recognition as sr

def __name__ == "__main__":
    rospy.init_node("speech_recognition")
    r = sr.Recognizer()
    with sr.Microphone() as source:
        audio = r.listen(source)
    recognized_speech = r.recognize_google(audio)
    pub = rospy.Publisher("recognized_speech", String, latch=True, queue_size=1)
    pub.publish(recognized_speech)
    rospy.spin()
