#!/usr/bin/env python

import rospy
from std_msgs.msg import String
import speech_recognition as sr

if __name__ == '__main__':
    rospy.init_node("speech_recognition")
    r = sr.Recognizer()
    pub = rospy.Publisher("recognized_speech", String, latch=True, queue_size=1)
    try:
        while not rospy.is_shutdown():
            with sr.Microphone() as source:
                audio = r.listen(source)
                try:
                    recognized_speech = r.recognize_google(audio)
                    print("You said: " + recognized_speech)
                    pub.publish(recognized_speech)
                except sr.UnknownValueError:
                    print("Could not understand audio")
                except sr.RequestError as e:
                    print("Could not request results; {0}".format(e))
        rospy.spin()
    except Exception as exc:
            print(exc)
