#!/usr/bin/env python
from __future__ import print_function
import rospy
from std_msgs.msg import String
import speech_recognition as sr

if __name__ == '__main__':
    rospy.init_node("speech_recognition")
    recognizer = sr.Recognizer()
    microphone = sr.Microphone()
    with microphone as source:
        recognizer.adjust_for_ambient_noise(source)
    pub = rospy.Publisher("recognized_speech", String, latch=True, queue_size=1)
    try:
        while not rospy.is_shutdown():
            print('Listening...')
            with microphone as source:
                audio = recognizer.listen(source)
            print('Got a sound; recognizing...')
            try:
                recognized_speech = recognizer.recognize_google(audio)
                print("You said: " + recognized_speech)
                pub.publish(recognized_speech)
            except sr.UnknownValueError:
                print("Could not understand audio")
            except sr.RequestError as e:
                print("Could not request results; {0}".format(e))
        rospy.spin()
    except Exception as exc:
        print(exc)
