#!/usr/bin/env python
import importlib

if __name__ == "__main__":
    #This  is an idea to implement an idea for a common script server for speech_recognition packages
    speech_actions_pkg = importlib.import_module('.speech_pose_saver',  package = 'mdr_speech_pose_saver')
    speech_actions_class = getattr(speech_actions_pkg, "SpeechPoseSaver")
    speech_class = speech_actions_class("navigation_goals.yaml")

    while not speech_class.is_exit_requested():
        pass
