#! /usr/bin/env python
import sys

import rospy
import roslib
import actionlib

from mdr_turn_base_to_action.msg import TurnBaseToAction, TurnBaseToActionGoal

def print_usage_info():
    rospy.loginfo('usage: enter_door_client_test')

if __name__ == '__main__':
    rospy.init_node('turn_base_to_client_test')

    client = actionlib.SimpleActionClient('/mdr_actions/turn_base_to_server', TurnBaseToAction)
    client.wait_for_server()

    goal = TurnBaseToActionGoal()
    if len(sys.argv) != 2:
        rospy.logerr('Action takes one argument')
        print_usage_info()
    else:
        try:
            timeout = 120.0
            rospy.loginfo('Sending action lib goal to turn_to_server angle: ' + sys.argv[1])
            goal.desired_yaw = sys.argv[1]
            client.send_goal(goal)
            client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
            print client.get_result()
        except:
            pass
