#! /usr/bin/env python
import sys

import rospy
import roslib
import actionlib

from mdr_turn_to_action.msg import TurnToAction, TurnToGoal

def print_usage_info():
    rospy.loginfo('usage: enter_door_client_test')

if __name__ == '__main__':
    rospy.init_node('turn_to_client_test')

    client = actionlib.SimpleActionClient('/mdr_actions/turn_to_server', TurnToAction)
    client.wait_for_server()

    goal = TurnToActionGoal()
    if len(sys.argv) != 1:
        rospy.logerr('Action takes no arguments')
        print_usage_info()
    else:
        try:
            timeout = 120.0
            rospy.loginfo('Sending action lib goal to turn_to_server')
            goal.desired_yaw = sys.argv[2]
            client.send_goal(goal)
            client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
            print client.get_result()
        except:
            pass
