#! /usr/bin/env python
from __future__ import print_function
import argparse
import rospy
import actionlib

from mdr_hand_over_action.msg import HandOverAction, HandOverGoal

if __name__ == '__main__':
    posture_contexts = ['standing', 'seated', 'lying']
    obstacle_contexts = [0, 1]                                 # 0: no obstacle, 1: obstacle
    release_detection = [0, 1]

    parser = argparse.ArgumentParser(description='help text')
    parser.add_argument("--posture", "-p", type=str, default='seated',
                        help="posture context parameters. Choose from 'standing', 'seated', or 'lying'.")
    parser.add_argument("--context_aware", "-c", action="store_true", dest="context_aware",
                        help="Use context-based handover")
    parser.add_argument("--obstacle_avoidance", "-o", action="store_true", dest="obstacle",
                        help="Use obstacle avoidance")
    parser.add_argument("--release_detection", "-r", action="store_true", dest="release_detection",
                        help="Use force-torque sensor for release detection")
    args = parser.parse_args()

    rospy.init_node('hand_over_action_client_test')

    client = actionlib.SimpleActionClient('/hand_over_server', HandOverAction)
    client.wait_for_server()

    goal = HandOverGoal()

    rospy.loginfo('Setting goal for a %s person, with %s obstacle in-between...' % (args.posture, 'an' if args.obstacle else 'no'))
    goal.posture_type = args.posture
    goal.obstacle = args.obstacle
    goal.release_detection = args.release_detection
    goal.context_aware = args.context_aware
    goal.person_pose.header.frame_id = "base_link"

    timeout = 15.0
    rospy.loginfo('Sending action lib goal to hand_over_server')
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
    print(client.get_result())
