# The area which is supposed to be cleaned
arm_navigation_msgs/Shape area

# The center of the area to be cleaned
geometry_msgs/PointStamped area_center

# The position of the sponge
geometry_msgs/PointStamped sponge_position

---

bool success
