# goal definition
string plane_config
string plane_frame_prefix
---
# result definition
bool success
mcr_perception_msgs/PlaneList recognized_planes
---
# feedback
string current_state
string message 
