#!/usr/bin/env python
import rospy
import smach

from smach_ros import ActionServerWrapper, IntrospectionServer

from mdr_place_action.msg import PlaceAction
from mdr_place_action.action_states import (SetupPlace, Place, SetActionLibResult)


class PlaceSkill(smach.StateMachine):
    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['OVERALL_SUCCESS',
                                              'OVERALL_FAILED', 'PREEMPTED'],
                                    input_keys=['place_goal'],
                                    output_keys=['place_feedback',
                                                 'place_result'])

        move_arm_server = rospy.get_param('~move_arm_server', 'move_arm_server')
        move_base_server = rospy.get_param('~move_base_server', 'move_base_server')
        gripper_controller_pkg_name = rospy.get_param('~gripper_controller_pkg_name',
                                                      'mdr_gripper_controller')
        preplace_config_name = rospy.get_param('~preplace_config_name', 'pregrasp')
        safe_arm_joint_config = rospy.get_param('~safe_arm_joint_config', 'folded')
        base_elbow_offset = float(rospy.get_param('~base_elbow_offset', -1.))
        placing_orientation = rospy.get_param('~placing_orientation', list())
        placing_dmp = rospy.get_param('~placing_dmp', '')
        dmp_tau = float(rospy.get_param('~dmp_tau', 1.))

        with self:
            smach.StateMachine.add('SETUP_PLACE', SetupPlace(),
                                   transitions={'succeeded': 'PLACE',
                                                'failed': 'SETUP_PLACE'})

            smach.StateMachine.add('PLACE', Place(move_arm_server=move_arm_server,
                                                  move_base_server=move_base_server,
                                                  gripper_controller_pkg_name=gripper_controller_pkg_name,
                                                  preplace_config_name=preplace_config_name,
                                                  safe_arm_joint_config=safe_arm_joint_config,
                                                  base_elbow_offset=base_elbow_offset,
                                                  placing_orientation=placing_orientation,
                                                  placing_dmp=placing_dmp,
                                                  dmp_tau=dmp_tau),
                                   transitions={'succeeded': 'SET_ACTION_LIB_SUCCESS',
                                                'failed': 'SET_ACTION_LIB_FAILED'})

            smach.StateMachine.add('SET_ACTION_LIB_FAILED',
                                   SetActionLibResult(False),
                                   transitions={'succeeded': 'OVERALL_FAILED'})

            smach.StateMachine.add('SET_ACTION_LIB_SUCCESS',
                                   SetActionLibResult(True),
                                   transitions={'succeeded': 'OVERALL_SUCCESS'})


if __name__ == '__main__':
    rospy.init_node('place_server')

    # construct state machine
    sm = PlaceSkill()

    # smach viewer
    sis = IntrospectionServer('place_smach_viewer', sm,
                              '/PLACE_SMACH_VIEWER')
    sis.start()

    asw = ActionServerWrapper(
        server_name='place_server',
        action_spec=PlaceAction,
        wrapped_container=sm,
        succeeded_outcomes=['OVERALL_SUCCESS'],
        aborted_outcomes=['OVERALL_FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='place_goal',
        feedback_key='place_feedback',
        result_key='place_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
