#!/usr/bin/python
import sys

import rospy
import smach
import smach_ros

from mdr_speech_person_recognition.action_states import Dummy


class DescribeCrowd(smach.StateMachine):
    """The speech and person recognition test"""
    def __init__(self, waypoint=''):
        smach.StateMachine.__init__(self, outcomes=['DONE', 'TIMEOUT'])
        self.waypoint = waypoint

        with self:
            smach.StateMachine.add('WAIT',
                                   Dummy(),
                                   transitions={
                                    'succeeded': 'FIND_CROWD',
                                    'failed': 'FIND_CROWD'})

            smach.StateMachine.add('FIND_CROWD',
                                   Dummy(),
                                   transitions={
                                    'succeeded': 'COUNT_CROWD',
                                    'failed': 'FIND_CROWD'})

            smach.StateMachine.add('COUNT_CROWD',
                                   Dummy(),
                                   transitions={
                                    'succeeded': 'RECOGNIZE_CROWD_GENDER',
                                    'failed': 'COUNT_CROWD'})

            smach.StateMachine.add('RECOGNIZE_CROWD_GENDER',
                                   Dummy(),
                                   transitions={
                                    'succeeded': 'DESCRIBE_RESULTS',
                                    'failed': 'RECOGNIZE_CROWD_GENDER'})

            smach.StateMachine.add('DESCRIBE_RESULTS',
                                   Dummy(),
                                   transitions={
                                    'succeeded': 'DONE',
                                    'failed': 'DESCRIBE_RESULTS'})

        rospy.loginfo("Describe Crowd SM initialized successfully")


def main():
    rospy.init_node('describe_crowd')

    SM = DescribeCrowd()

    smach_viewer = smach_ros.IntrospectionServer('describe_crowd',
                                                 SM,
                                                 'DESCRIBE_CROWD')
    smach_viewer.start()

    result = SM.execute()
    while (result is None):
        rospy.spin()
    rospy.loginfo('Describe crowd complete.')
    smach_viewer.stop()


if __name__ == '__main__':
    main()
