#! /usr/bin/env python
from __future__ import print_function
import rospy
import actionlib

from mdr_pull_action.msg import PullAction, PullGoal


if __name__ == '__main__':
    rospy.init_node('pull_action_client_test')

    client = actionlib.SimpleActionClient('/pull_server', PullAction)
    client.wait_for_server()

    goal = PullGoal()
    timeout = 15.0
    rospy.loginfo('Sending action lib goal to pull_server')
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
    print(client.get_result())
