#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on 2018.10.19

@author: Patrick Nagel, Roberto Cai
"""

import sys

import rospy
import actionlib

from mdr_execute_command_action.msg import ExecutionAction, ExecutionGoal


def print_usage_info():
    rospy.loginfo("usage: execute <command>")
    rospy.loginfo("       where <command> is a string")


if __name__ == '__main__':
    rospy.init_node('execute_client_test')
    client = actionlib.SimpleActionClient('execute_command_server', ExecutionAction)
    client.wait_for_server()

    try:
        goal = ExecutionGoal()
        user_input_command = sys.argv[1]
        goal.command = user_input_command
        timeout = 15.0
        rospy.loginfo("Sending action lib goal to execute_command_server, command: "
                      + goal.command)
        client.send_goal(goal)
        client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
        print client.get_result()
    except:
        rospy.logerr("An exception has been thrown")
        print_usage_info()
