#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 26 14:58:27 2018

@author: patrick
"""

import rospy

from std_msgs.msg import String
from tmc_rosjulius_msgs.msg import RecognitionResult
from mdr_listen_action.SpeechVerifier import SpeechVerifier

def callback(self, data):
        rospy.loginfo(rospy.get_caller_id() + " I heard %s ", data.sentences)
        sv = SpeechVerifier("../../../common/config/dict", "../../../common/config/sentence_pool.txt", data.sentences)
        accoustic_input = sv.find_best_match()
        pub = rospy.Publisher('recognized_speech', String, queue_size=10)
        pub.publish(accoustic_input)

def main():
    rospy.init_node("listener")
    rospy.Subscriber("hsrb/voice/text", RecognitionResult, callback)
    rospy.spin()