#! /usr/bin/env python
import rospy
import actionlib
from mdr_find_object_action.msg import FindObjectAction, FindObjectGoal

if __name__ == '__main__':
    rospy.init_node('find_object_client_test')
    client = actionlib.SimpleActionClient('find_object_server', FindObjectAction)
    client.wait_for_server()
    goal = FindObjectGoal()
    goal.goal_type = FindObjectGoal.NAMED_OBJECT
    goal.object_name = 'CoffeeMug'
    try:
        timeout = 45.0
        rospy.loginfo('Sending action lib goal to find_object_server')
        client.send_goal(goal)
        client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
        rospy.loginfo(client.get_result())
    except:
        pass
