#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on 2019.10.09

@author: Roberto Cai
@email: roberto.cai@smail.inf.h-brs.de
"""

import sys

import rospy
import roslib
import actionlib

from mdr_listen_action.msg import ListenAction, ListenGoal

if __name__ == '__main__':
    rospy.init_node('listen_client_test')
    client = actionlib.SimpleActionClient('listen_server', ListenAction)
    client.wait_for_server()

    goal = ListenGoal()
    try:
        client.send_goal(goal)
        timeout = 10.0
        client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
        rospy.loginfo(client.get_result())

    except Exception as ex:
        rospy.logerr(type(ex).__name__ + ": You have failed!")
