#!/usr/bin/env python
import rospy

from mdr_sound_vocalisation.sound_vocaliser_base import SoundVocaliserBase

if __name__ == '__main__':
    rospy.init_node('mdr_sound_vocaliser')
    try:
        SoundVocaliserBase()
    except rospy.ROSInterruptException:
        pass
