#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on 2017.09.21

@author: Patrick Nagel
"""

import sys

import rospy
import roslib
import actionlib

from mdr_speech_actions.msg import ListenAction, ListenGoal

def print_usage_info():
    rospy.loginfo("usage: listen <duration>")
    rospy.loginfo("       where <duration> is measured in minutes")

if __name__ == '__main__':
    rospy.init_node('listen_client_test')
    client = actionlib.SimpleActionClient('listen_server', ListenAction)
    client.wait_for_server()

    goal = ListenGoal()
    user_input_duration = sys.argv[1]
    try:
        user_input_duration = int(user_input_duration)
        goal.listen_duration = user_input_duration
        timeout = 15.0
        rospy.loginfo("Sending action lib goal to listen_server, duration: "\
         + str(goal.listen_duration))
        client.send_goal(goal)
        client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
        print client.get_result()

    except ValueError:
        rospy.logerr("Received unknown value for <duration> argument")
        print_usage_info()


