#! /usr/bin/env python
from __future__ import print_function
import rospy
import actionlib
import numpy as np

from mdr_recognize_gesture_action.msg import RecognizeGestureAction, RecognizeGestureGoal


if __name__ == '__main__':
    rospy.init_node('recognize_gesture_action_client_test')

    client = actionlib.SimpleActionClient('/recognize_gesture_server', RecognizeGestureAction)
    client.wait_for_server()

    goal = RecognizeGestureGoal()
    goal.gesture_type = 'pointing'

    timeout = 15.0
    rospy.loginfo('Sending action lib goal to recognize_gesture_server')
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
    print(client.get_result())
