#!/usr/bin/env python

import rospy
from mdr_mbot_interface.mbot_planner import MbotPlanner

if __name__ == '__main__':
    rospy.init_node('mbot_planner', anonymous=False)
    planner = MbotPlanner()
    planner.wait_for_interpretation()
