#!/usr/bin/env python
from __future__ import print_function
from os import listdir
from os.path import join, isfile
import rospy

from mdr_component_monitoring.config.config_file_reader import ComponentMonitorConfigFileReader
from mdr_component_monitoring.monitor_manager import MonitorManager

def get_files(dir_name):
    file_names = list()
    for f_name in listdir(dir_name):
        f_path = join(dir_name, f_name)
        if isfile(f_path):
            file_names.append(f_name)
    return file_names

if __name__ == '__main__':
    rospy.init_node('mdr_component_monitoring')
    hw_monitor_config_dir_name = rospy.get_param('~hw_monitor_config_dir', '../../monitor_config/hardware')
    sw_monitor_config_dir_name = rospy.get_param('~sw_monitor_config_dir', '../../monitor_config/software')

    hw_config_files = get_files(hw_monitor_config_dir_name)
    hw_monitor_config_params = list()
    for config_file in hw_config_files:
        component_config_params = ComponentMonitorConfigFileReader.load(hw_monitor_config_dir_name,
                                                                        config_file)
        hw_monitor_config_params.append(component_config_params)

    sw_config_files = get_files(sw_monitor_config_dir_name)
    sw_monitor_config_params = list()
    for config_file in sw_config_files:
        component_config_params = ComponentMonitorConfigFileReader.load(sw_monitor_config_dir_name,
                                                                        config_file)
        sw_monitor_config_params.append(component_config_params)

    monitor_manager = MonitorManager(hw_monitor_config_params, sw_monitor_config_params)
    monitor_manager.monitor_components()
