# goal
geometry_msgs/PoseStamped pose        # pose at which the object should be placed
bool release_on_impact                # whether the object should be released only if
                                      # impact with a placing surface is detected
---
# result
bool success
---
# feedback
string current_state
string message
