#! /usr/bin/env python
import sys

import rospy
import roslib
import actionlib

from mdr_move_tray_action.msg import MoveTrayAction, MoveTrayGoal

def print_usage_info():
    rospy.loginfo('usage: move_tray <direction>')
    rospy.loginfo('       where <direction> can be either up or down')

if __name__ == '__main__':
    rospy.init_node('move_tray_client_test')

    client = actionlib.SimpleActionClient('/mdr_actions/move_tray_server', MoveTrayAction)
    client.wait_for_server()

    goal = MoveTrayGoal()
    if len(sys.argv) != 2:
        rospy.logerr('Arguments were not received in the proper format')
        print_usage_info()
    else:
        try:
            goal.direction = sys.argv[1].lower()
            if goal.direction != MoveTrayGoal.UP and goal.direction != MoveTrayGoal.DOWN:
                rospy.logerr('Received unknown value for <direction> argument')
                print_usage_info()
            else:
                timeout = 15.0
                rospy.loginfo('Sending action lib goal to move_tray_server, direction: ' + goal.direction)
                client.send_goal(goal)
                client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
                print client.get_result()
        except:
            pass
