#!/usr/bin/env python
import rospy
import actionlib

from mdr_push_action.msg import PushAction, PushGoal

if __name__ == '__main__':
    rospy.init_node('push_action_client_test')

    client = actionlib.SimpleActionClient('push_server', PushAction)
    client.wait_for_server()

    goal = PushGoal()
    goal.object_pose.header.frame_id = 'base_link'
    goal.object_pose.header.stamp = rospy.Time.now()

    goal.object_pose.pose.position.x = 0.418
    goal.object_pose.pose.position.y = 0.078
    goal.object_pose.pose.position.z = 0.842

    goal.object_pose.pose.orientation.x = 0.758
    goal.object_pose.pose.orientation.y = 0.000
    goal.object_pose.pose.orientation.z = 0.652
    goal.object_pose.pose.orientation.w = 0.000

    goal.goal_pose.header.frame_id = 'base_link'
    goal.goal_pose.header.stamp = rospy.Time.now()

    goal.goal_pose.pose.position.x = 0.518
    goal.goal_pose.pose.position.y = 0.078

    client.send_goal(goal)
    client.wait_for_result()

    rospy.loginfo(client.get_result())
