#! /usr/bin/env python
from __future__ import print_function
import rospy
import actionlib

from mdr_push_action.msg import PushAction, PushGoal


if __name__ == '__main__':
    rospy.init_node('push_action_client_test')

    client = actionlib.SimpleActionClient('/push_server', PushAction)
    client.wait_for_server()

    goal = PushGoal()
    timeout = 15.0
    rospy.loginfo('Sending action lib goal to push_server')
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
    print(client.get_result())
