#! /usr/bin/env python
from __future__ import print_function
import rospy
import actionlib

from mdr_push_action.msg import PushAction, PushGoal


if __name__ == '__main__':
    rospy.init_node('push_action_client_test')

    client = actionlib.SimpleActionClient('/push_server', PushAction)
    client.wait_for_server()
    goal = PushGoal()

    goal.init_end_effector_pose.header.frame_id = 'base_link'
    goal.init_end_effector_pose.header.stamp = rospy.Time.now()

    goal.init_end_effector_pose.pose.position.x = 0.418
    goal.init_end_effector_pose.pose.position.y = 0.078
    goal.init_end_effector_pose.pose.position.z = 0.842

    goal.init_end_effector_pose.pose.orientation.x = 0.758
    goal.init_end_effector_pose.pose.orientation.y = 0.000
    goal.init_end_effector_pose.pose.orientation.z = 0.652
    goal.init_end_effector_pose.pose.orientation.w = 0.000
    

    timeout = 15.0
    rospy.loginfo('Sending action lib goal to push_server')
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
    print(client.get_result())
