#! /usr/bin/env python
import sys

import rospy
import roslib
import actionlib

from mdr_enter_door_action.msg import EnterDoorAction, EnterDoorGoal

def print_usage_info():
    rospy.loginfo('usage: enter_door_client_test')

if __name__ == '__main__':
    rospy.init_node('enter_door_client_test')

    client = actionlib.SimpleActionClient('/mdr_actions/enter_door_server', EnterDoorAction)
    client.wait_for_server()

    goal = EnterDoorGoal()
    if len(sys.argv) != 1:
        rospy.logerr('Action takes no arguments')
        print_usage_info()
    else:
        try:
            timeout = 120.0
            rospy.loginfo('Sending action lib goal to enter_door_server')
            client.send_goal(goal)
            client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
            print client.get_result()
        except:
            pass
