#!/usr/bin/env python
import os
from importlib import import_module
import rospy
from mdr_perception_libs.srv import ImageRecognition, ImageRecognitionResponse
from mdr_perception_libs import ImageClassifier


class RecognizeImageService(object):
    def __init__(self, classifer_class, model_dir):
        if not issubclass(classifer_class, ImageClassifier):
            raise ValueError('classifer is not of ImageClassifier type')

        self._classifier_class = classifer_class
        self._model_dir = model_dir

        # dictionary of classifiers - key is the model_path
        self._classifiers = {}
        self._recog_service = rospy.Service('recognize_image', ImageRecognition, self.handle_recognize_image)

    def handle_recognize_image(self, req):
        print('\nnumber of images: ' + str(len(req.images)) + '\n')
        if req.model_name not in self._classifiers:
            model_path = os.path.join(self._model_dir, req.model_name + '.h5')
            class_file = os.path.join(self._model_dir, req.model_name + '.txt')
            rospy.loginfo('recognition model path: ' + model_path)
            rospy.loginfo('recognition class file path: ' + class_file)
            self._classifiers[req.model_name] = self._classifier_class(model_path=model_path, class_file=class_file)

        indices, classes, probabilities = self._classifiers[req.model_name].classify(req.images)
        response = ImageRecognitionResponse()
        response.indices = indices
        response.classes = classes
        response.probabilities = probabilities
        return response


if __name__ == '__main__':
    rospy.init_node('~image_recognition_server')
    model_dir = rospy.get_param('~model_directory', '')
    if model_dir is None:
        from rospkg import ResourceNotFound, RosPack
        try:
            rp = RosPack()
            model_dir = os.path.join(rp.get_path('mdr_perception_libs'), 'models')
        except ResourceNotFound as e:
            rospy.logerr(e.message)
            raise

    recog_module = rospy.get_param('~recognition_module', 'mdr_perception_libs')
    recog_class_name = rospy.get_param('~recognition_class', 'ImageClassifierTest')
    recog_class = getattr(import_module(recog_module), recog_class_name)
    RecognizeImageService(recog_class, model_dir)
    rospy.spin()
