#! /usr/bin/env python
import sys

import rospy
import roslib
import actionlib

from mdr_detect_person.msg import DetectPersonAction, DetectPersonGoal, DetectPersonFeedback, DetectPersonResult

if __name__ == '__main__':
    rospy.init_node('detect_person_client_test')

    client = actionlib.SimpleActionClient('mdr_actions/detect_person_server', DetectPersonAction)
    client.wait_for_server()
    goal = DetectPersonGoal()
    goal.start = True
    client.send_goal(goal)
    client.wait_for_result()
    print (client.get_result())

