#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on 2017.10.19

@author: Patrick Nagel, Roberto Cai
"""

import rospy
import smach

from smach_ros import ActionServerWrapper, IntrospectionServer
from mdr_process_speech_command_action.msg import ProcessSpeechAction, ProcessSpeechResult, ProcessSpeechFeedback
from mdr_process_speech_command_action.action_states import InitializeProcessSpeechCommand, InitializationError,\
                                    MatchCommand, MatchError


class ProcessSpeechCommandSkill(smach.StateMachine):

    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['OVERALL_SUCCESS', 'OVERALL_FAILED', 'PREEMPTED'],
                                    input_keys=['process_speech_command_goal'],
                                    output_keys=['process_speech_command_feedback', 'process_speech_command__result'])
        with self:
            smach.StateMachine.add('INITIALIZE_PROCESS_SPEECH_COMMAND', InitializeProcessSpeechCommand(),
                                   transitions={'succeeded':'MATCH_COMMAND',
                                                'failed':'INITIALIZATION_ERROR',
                                                'processing':'INITIALIZE_PROCESS_SPEECH_COMMAND'})
            smach.StateMachine.add('INITIALIZATION_ERROR', InitializationError(),
                                   transitions={'error_detected':'OVERALL_FAILED',
                                                'processing':'INITIALIZATION_ERROR'})
            smach.StateMachine.add('MATCH_COMMAND', MatchCommand(),
                                   transitions={'succeeded':'OVERALL_SUCCESS',
                                                'command_not_found':'MATCH_ERROR',
                                                'processing':'MATCH_COMMAND'})
            smach.StateMachine.add('MATCH_ERROR', MatchError(),
                                   transitions={'error_detected':'OVERALL_FAILED',
                                                'processing':'MATCH_ERROR'})


if __name__ == '__main__':
    rospy.init_node('process_speech_command_server')

    # construct state machine
    sm = ProcessSpeechCommandSkill()

    # smach viewer
    sis = IntrospectionServer('process_speech_command_smach_viewer', sm, '/PROCESS_SPEECH_COMMAND_SMACH_VIEWER')
    sis.start()

    # construct the action server wrapper
    asw = ActionServerWrapper(
        server_name='process_speech_command_server',
        action_spec=ProcessSpeechAction,
        wrapped_container=sm,
        succeeded_outcomes=['OVERALL_SUCCESS'],
        aborted_outcomes=['OVERALL_FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='process_speech_command_goal',
        feedback_key='process_speech_command_feedback',
        result_key='process_speech_command_result')

    # Run the server in the background thread
    asw.run_server()
    rospy.spin()
