#!/usr/bin/env python
from std_srvs.srv import Empty, EmptyResponse
import rospy
from mdr_object_recognition import EMPTY_DETECTION_SERVICE


def handle_empty_request(_):
    return EmptyResponse()


def object_detection_test_server():
    rospy.init_node('object_detection_test_server')
    rospy.Service(EMPTY_DETECTION_SERVICE, Empty, handle_empty_request)
    rospy.spin()

if __name__ == "__main__":
    object_detection_test_server()
