# Description: part of the Speech and Person Recognition scenario
# in RoboCup@Home
# Author: Argentina Ortega Sainz
sm_id: describe_crowd
states:
  - WAIT
  - FIND_CROWD
  - DETECT_PERSONS
  - RECOGNIZE_GENDER
  - DESCRIBE_RESULTS
outcomes: [DONE, TIMEOUT]
state_descriptions:
  - state:
      name: WAIT
      state_module_name: mdr_speech_person_recognition.action_states
      state_class_name: Wait
      transitions:
          - transition:
              name: succeeded
              state: FIND_CROWD
      arguments:
          - argument:
              name: timeout
              value: 5 # Wait 5 seconds
  - state: # Needs to be implemented, can be just turn 180°
    name: FIND_CROWD
  - state:
    name: DETECT_PERSONS
    state_module_name: mdr_detect_person.skill
    state_class_name: DetectPersonSkill
    transitions:
      - transition:
        name: OVERALL_SUCCESS
        state: RECOGNIZE_GENDER
      - transition:
        name: OVERALL_FAILED
        state: DETECT_PERSONS
      - transition:
        name: PREEMPTED
        state: DETECT_PERSONS
  - state:
    name: RECOGNIZE_GENDER
    state_module_name: mdr_gender_recognition.skill
    state_class_name: GenderRecognitionSkill
    transitions:
      - transition:
        name: OVERALL_SUCCESS
        state: DESCRIBE_RESULTS
      - transition:
        name: OVERALL_FAILED
        state: RECOGNIZE_GENDER
      - transition:
        name: PREEMPTED
        state: RECOGNIZE_GENDER
  - state:
    name: DESCRIBE_RESULTS
    state_module_name: mdr_speech_person_recognition.action_states
    state_class_name: DescribeResults
    transitions:
      - transition:
        name: succeeded
        state: DONE
    arguments: # What about argument passing between states?
      - argument:
        name: topic
        value: '/say'
      - argument:
        name: crowd_size
        value:
      - argument:
        name: men
        value:
      - argument:
        name: women
        value:
