sm_id: speech_and_person_recognition
states:
  - ENTER
  - GO_TO_TEST_WAYPOINT
  - DESCRIBE_CROWD
  - RIDDLE_GAME
  - BLIND_MANS_BLUFF
outcomes: [DONE, TIMEOUT]
state_descriptions:
  - state:
    name: 
