# Description: Defines a state machine for a RoboCup@Home store groceries scenario
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: mdr_store_groceries
states: [GO_TO_TABLE, PERCEIVE_TABLE, PICK_OBJECT1, GO_TO_CUPBOARD]
outcomes: [DONE, TIMEOUT, FAILED]
state_descriptions:
    - state:
        name: GO_TO_TABLE
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: PERCEIVE_TABLE
            - transition:
                name: failed
                state: GO_TO_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [dining_table]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PERCEIVE_TABLE
        state_module_name: mdr_perception_behaviours.perceive_planes_zain_test
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: PICK_OBJECT1
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: plane_prefix
                value: table 
            # - argument:
                # name: clear_memory
                # value: True
                
    - state:
        name: PICK_OBJECT1
        state_module_name: mdr_manipulation_behaviours.pick_closest_from_surface
        state_class_name: PickClosestFromSurface
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_CUPBOARD
            - transition:
                name: failed
                state: GO_TO_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
            - transition:
                name: find_objects_before_picking
                state: PERCEIVE_TABLE
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: picking_surface_prefix
                value: table                                          
    - state:
        name: GO_TO_CUPBOARD
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: DONE
            - transition:
                name: failed
                state: GO_TO_CUPBOARD
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [shelf]
            - argument:
                name: number_of_retries
                value: 3
    # - state:
    #     name: SCAN_CUPBOARD
    #     state_module_name: mas_hsr_store_groceries.scenario_states.scan_shelf
    #     state_class_name: ScanShelf
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: PERCEIVE_SHELF
    #         - transition:
    #             name: failed
    #             state: SCAN_CUPBOARD
    #     # arguments:
    #     #     - argument:
    #     #         name: arm_joints
    #     #         value:
    #     #             arm_lift_joint: 0.2
    #     #             arm_roll_joint: 1.57
    #     #             wrist_flex_joint: -1.57
    #     #     - argument:
    #     #         name: head_joints
    #     #         value:
    #     #             head_tilt_joint: -0.2

    # - state:
    #     name: FIND_OBJECTS_BEFORE_PICKING
    #     state_module_name: mdr_perception_behaviours.perceive_planes
    #     state_class_name: PerceivePlanes
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: PICK_OBJECT1
    #         - transition:
    #             name: failed
    #             state: PERCEIVE_TABLE
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 3
    #         - argument:
    #             name: plane_prefix
    #             value: table  
                    

    # - state:
    #     name: PERCEIVE_SHELF
    #     state_module_name: mdr_perception_behaviours.perceive_planes_zain_test
    #     state_class_name: PerceivePlanes
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: PLACE_OBJECT
    #         - transition:
    #             name: failed
    #             state: PERCEIVE_SHELF
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 3
    #         - argument:
    #             name: plane_prefix
    #             value: shelf
    #         # - argument:
    #             # name: clear_memory
    #             # value: False
            
    # - state:
    #     name: PLACE_OBJECT
    #     state_module_name: mdr_manipulation_behaviours.place_based_on_category
    #     state_class_name: PlaceBasedOnCategory
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: GO_BACK_TO_TABLE
    #         - transition:
    #             name: failed
    #             state: PLACE_OBJECT
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 3
    #         - argument:
    #             name: placing_surface_prefix
    #             value: shelf
    # - state:
    #     name: GO_BACK_TO_TABLE
    #     state_module_name: mdr_navigation_behaviours.move_base
    #     state_class_name: MoveBase
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: GO_TO_TABLE
    #         - transition:
    #             name: failed
    #             state: GO_BACK_TO_TABLE
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: destination_locations
    #             value: [living_room_cabinet]
    #         - argument:
    #             name: number_of_retries
    #             value: 3
