# Description: Defines a state machine for a simple pick and place scenario (picking an object and placing it back on the same surface)
# Author: Heartmet_Team
# Email: unknown
sm_id: heartmet_task_full
states: [DETECT_PERSON_INITIAL, GO_TO_READING,DETECT_PERSON_READING ,GO_TO_SCAN ,GO_TO_DINING_FRONT,GO_TO_LIVING, DETECT_PERSON_DINING, DETECT_PERSON_HALL, DETECT_PERSON_LIVING, ORDER,GO_TO_LOCATION,GO_TO_HALL,PERCEIVE_TABLE,PICK_OBJECT,GO_TO_PERSON,HAND_OVER,DETECT_PERSON_FRONT,DETECT_PERSON_LEFT,DETECT_PERSON_RIGHT,IDENTIFY_POSTURE]
# states: [GO_TO_LIVING, DETECT_PERSON_DINING, DETECT_PERSON_HALL, DETECT_PERSON_LIVING, ORDER,GO_TO_LOCATION,GO_TO_HALL,PERCEIVE_TABLE,PICK_OBJECT,GO_TO_PERSON,HAND_OVER,DETECT_PERSON_FRONT,DETECT_PERSON_LEFT,DETECT_PERSON_RIGHT,IDENTIFY_POSTURE]

outcomes: [DONE, FAILED]
state_descriptions:
    # - state:
    #     name: DETECT_PERSON_INITIAL
    #     state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_front
    #     state_class_name: DetectPerson
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: GO_TO_READING
    #         - transition:
    #             name: failed
    #             state: DETECT_PERSON_INITIAL
    #         - transition:
    #             name: failed_after_retrying
    #             state: GO_TO_SCAN
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 2
    # - state:
    #     name: GO_TO_READING
    #     state_module_name: mdr_navigation_behaviours.move_base
    #     state_class_name: MoveBase
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: DETECT_PERSON_READING
    #         - transition:
    #             name: failed
    #             state: GO_TO_READING
    #         - transition:
    #             name: failed_after_retrying
    #             state: GO_TO_SCAN
    #     arguments:
    #         - argument:
    #             name: destination_locations
    #             value: [reading_room]
    #         - argument:
    #             name: number_of_retries
    #             value: 3
    # - state:
    #     name: GO_TO_SCAN
    #     state_module_name: mdr_navigation_behaviours.move_base
    #     state_class_name: MoveBase
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: DETECT_PERSON_DINING
    #         - transition:
    #             name: failed
    #             state: GO_TO_SCAN
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: destination_locations
    #             value: [scan]
    #         - argument:
    #             name: number_of_retries
    #             value: 3

    # - state:
    #     name: DETECT_PERSON_READING
    #     state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_front
    #     state_class_name: DetectPerson
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: ORDER
    #         - transition:
    #             name: failed
    #             state: DETECT_PERSON_READING
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 2
    #         - argument:
    #             name: person_location
    #             value: [reading_room]
            
    # - state:
    #     name: DETECT_PERSON_DINING
    #     state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_front
    #     state_class_name: DetectPerson
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: GO_TO_DINING_FRONT
    #         - transition:
    #             name: failed
    #             state: DETECT_PERSON_DINING
    #         - transition:
    #             name: failed_after_retrying
    #             state: DETECT_PERSON_HALL
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 2
    #         - argument:
    #             name: person_location
    #             value: [dining_room]
    # - state:
    #     name: GO_TO_DINING_FRONT
    #     state_module_name: mdr_navigation_behaviours.move_base
    #     state_class_name: MoveBase
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: ORDER
    #         - transition:
    #             name: failed
    #             state: GO_TO_DINING_FRONT
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: destination_locations
    #             value: [dining]
    #         - argument:
    #             name: number_of_retries
    #             value: 3
    # - state:
    #     name: DETECT_PERSON_HALL
    #     state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_right
    #     state_class_name: DetectPerson
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: GO_TO_HALL
    #         - transition:
    #             name: failed
    #             state: DETECT_PERSON_HALL
    #         - transition:
    #             name: failed_after_retrying
    #             state: DETECT_PERSON_LIVING
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 2
    #         - argument:
    #             name: person_location
    #             value: [hall]
    # - state:
    #     name: GO_TO_HALL
    #     state_module_name: mdr_navigation_behaviours.move_base
    #     state_class_name: MoveBase
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: ORDER
    #         - transition:
    #             name: failed
    #             state: GO_TO_HALL
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: destination_locations
    #             value: [hall]
    #         - argument:
    #             name: number_of_retries
    #             value: 3

    # - state:
    #     name: DETECT_PERSON_LIVING
    #     state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_left
    #     state_class_name: DetectPerson
    #     transitions:
    #         - transition:
    #             name: succeeded
    #             state: GO_TO_LIVING
    #         - transition:
    #             name: failed
    #             state: DETECT_PERSON_LIVING
    #         - transition:
    #             name: failed_after_retrying
    #             state: FAILED
    #     arguments:
    #         - argument:
    #             name: number_of_retries
    #             value: 2
    #         - argument:
    #             name: person_location
    #             value: [living_room]
    - state:
        name: GO_TO_LIVING
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: ORDER
            - transition:
                name: failed
                state: GO_TO_LIVING
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [living_room]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: ORDER
        state_module_name: mdr_hri_behaviours.retrieve_information
        state_class_name: InteractionClient
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_LOCATION
            - transition:
                name: failed
                state: ORDER
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: GO_TO_LOCATION
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: PERCEIVE_TABLE
            - transition:
                name: failed
                state: GO_TO_LOCATION
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PERCEIVE_TABLE
        state_module_name: mdr_perception_behaviours.perceive_planes
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: PICK_OBJECT
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: plane_prefix
                value: table
    - state:
        name: PICK_OBJECT
        state_module_name: mdr_manipulation_behaviours.pick_closest_from_surface
        state_class_name: PickClosestFromSurface
        transitions:
            - transition:
                name: succeeded
                state: DONE
                
            # redundant state (if no use, remove it)
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
            - transition:
                name: find_objects_before_picking
                state: PERCEIVE_TABLE
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: picking_surface_prefix
                value: table
    - state:
        name: GO_TO_PERSON
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: DETECT_PERSON_FRONT
            - transition:
                name: failed
                state: GO_TO_PERSON
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: DETECT_PERSON_FRONT
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_front
        state_class_name: DetectPerson
        transitions:
            - transition:
                name: succeeded
                state: IDENTIFY_POSTURE
            - transition:
                name: failed
                state: DETECT_PERSON_FRONT
            - transition:
                name: failed_after_retrying
                state: DETECT_PERSON_RIGHT
        arguments:
            - argument:
                name: number_of_retries
                value: 2
    - state:
        name: DETECT_PERSON_RIGHT
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_right
        state_class_name: DetectPerson
        transitions:
            - transition:
                name: succeeded
                state: IDENTIFY_POSTURE
            - transition:
                name: failed
                state: DETECT_PERSON_RIGHT
            - transition:
                name: failed_after_retrying
                state: DETECT_PERSON_LEFT
        arguments:
            - argument:
                name: number_of_retries
                value: 2
    - state:
        name: DETECT_PERSON_LEFT
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_left
        state_class_name: DetectPerson
        transitions:
            - transition:
                name: succeeded
                state: IDENTIFY_POSTURE
            - transition:
                name: failed
                state: DETECT_PERSON_LEFT
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 2   
    - state:
        name: IDENTIFY_POSTURE
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.identify_posture
        state_class_name: IdentifyPosture
        transitions:
            - transition:
                name: succeeded
                state: HAND_OVER
            - transition:
                name: failed
                state: DETECT_PERSON_FRONT
        arguments:
            - argument:
                name: posture_height_width_ratio_ranges
                value:
                    standing: [1.65, 6.0]
                    seated: [0.6, 1.65]
                    lying: [0.0, 0.6]     
    - state:
        name: HAND_OVER
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.hand_over
        state_class_name: HandOver
        transitions:
            - transition:
                name: succeeded
                state: DONE
            - transition:
                name: failed
                state: HAND_OVER
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: obstacle_present
                value: False
            - argument:
                name: context_aware
                value: True
            - argument:
                name: release_detection
                value: True


