# Description: Defines a state machine for a simple pick and place scenario (picking an object and placing it back on the same surface)
# Author: Heartmet_Team
# Email: unknown
sm_id: heartmet_demo_item_delivery
states: [GO_TO_TABLE, PERCEIVE_TABLE, PICK_OBJECT, GO_TO_PERSON, DETECT_PERSON, IDENTIFY_POSTURE, HAND_OVER]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: GO_TO_TABLE
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: PERCEIVE_TABLE
            - transition:
                name: failed
                state: GO_TO_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [table1]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PERCEIVE_TABLE
        state_module_name: mdr_perception_behaviours.perceive_planes
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: PICK_OBJECT
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: plane_prefix
                value: table
    - state:
        name: PICK_OBJECT
        state_module_name: mdr_manipulation_behaviours.pick_closest_from_surface
        state_class_name: PickClosestFromSurface
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_PERSON
                
            # redundant state (if no use, remove it)
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
            - transition:
                name: find_objects_before_picking
                state: PERCEIVE_TABLE
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: picking_surface_prefix
                value: table
    - state:
        name: GO_TO_PERSON
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: DETECT_PERSON
            - transition:
                name: failed
                state: GO_TO_PERSON
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [person1]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: DETECT_PERSON
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.detect_person_front
        state_class_name: DetectPerson
        transitions:
            - transition:
                name: succeeded
                state: IDENTIFY_POSTURE
            - transition:
                name: failed
                state: DETECT_PERSON
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: IDENTIFY_POSTURE
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.identify_posture
        state_class_name: IdentifyPosture
        transitions:
            - transition:
                name: succeeded
                state: HAND_OVER
            - transition:
                name: failed
                state: DETECT_PERSON
        arguments:
            - argument:
                name: posture_height_width_ratio_ranges
                value:
                    standing: [1.65, 6.0]
                    seated: [0.6, 1.65]
                    lying: [0.0, 0.6]
    - state:
        name: HAND_OVER
        state_module_name: mdr_demo_context_aware_hand_over.scenario_states.hand_over
        state_class_name: HandOver
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_TABLE
            - transition:
                name: failed
                state: HAND_OVER
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: obstacle_present
                value: False
            - argument:
                name: context_aware
                value: True
            - argument:
                name: release_detection
                value: True
