# Description: Defines a state machine for a simple pick and place scenario (picking an object and placing it back on the same surface)
# Author: Heartmet_Team
# Email: unknown
sm_id: heartmet_demo_item_delivery
states: [ORDER,GO_TO_LOCATION]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: ORDER
        state_module_name: mdr_hri_behaviours.order_taking
        state_class_name: OrderTaking
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_LOCATION
            - transition:
                name: failed
                state: ORDER
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: GO_TO_LOCATION
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: DONE
            - transition:
                name: failed
                state: GO_TO_LOCATION
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            