#! /usr/bin/env python
import sys

import rospy
import roslib
import actionlib

from mdr_move_forward_action.msg import MoveForwardAction, MoveForwardGoal

def print_usage_info():
    rospy.loginfo('usage: move_forward_action <duration>')
    rospy.loginfo('       where <duration> is the time (in seconds) for which the robot should move')
    rospy.loginfo('             <speed> is the movement speed (in m/s)')

if __name__ == '__main__':
    rospy.init_node('move_forward_action_client_test')

    client = actionlib.SimpleActionClient('/mdr_actions/move_forward_server', MoveForwardAction)
    client.wait_for_server()

    goal = MoveForwardGoal()
    if len(sys.argv) != 3:
        rospy.logerr('Arguments were not received in the proper format')
        print_usage_info()
    else:
        try:
            try:
                goal.movement_duration = float(sys.argv[1])
            except ValueError:
                rospy.logerr('Incorrect value for the <duration> argument')
                print_usage_info()

            try:
                goal.speed = float(sys.argv[2])
            except ValueError:
                rospy.logerr('Incorrect value for the <speed> argument')
                print_usage_info()

            rospy.loginfo('Sending action lib goal to move_forward_server, duration: ' + str(goal.movement_duration) + ', speed: ' + str(goal.speed))
            client.send_goal(goal)
            client.wait_for_result()
            print client.get_result()
        except:
            pass
