#!/usr/bin/env python
import rospy

from mdr_gripper_controller.gripper_controller_base import GripperControllerBase

if __name__ == '__main__':
    rospy.init_node('mdr_gripper_controller')
    try:
        GripperControllerBase()
    except rospy.ROSInterruptException:
        pass
