Success: B/BSuccess.wav
Error: B/BBeepThinking.wav
Continue: B/BGoAhead.wav
Waiting: B/BHmm.wav
Help: B/BPleaseHelp2.wav
Receive: E/E01.wav
Run: E/E06.wav
Wait: E/E07.wav
Request: E/E09.wav
State: E/E12.wav
