Bell: D/DC01a.wav
Ring1: D/D02p.wav
Ring2: G/G25.wav
Alarm1: D/D04.wav
Alarm2: D/D05.wav
Alarm3: D/D09.wav
Alarm4: D/D17.wav
Alarm5: D/D23.wav
Alarm6: D/D32.wav
Alarm7: D/DOuch.wav
Ring: F/F01.wav
StandardRing: F/F06.wav
LongRing: F/F09.wav
HighPriority: F/F10.wav
LowWarning: F/F12.wav
HighWarning: F/F14.wav
Warning: G/G01.wav
Noise1: G/G03.wav
Noise2: G/G11.wav
Noise3: G/G17.wav
RepetitiveNoise1: G/G20.wav
RepetitiveNoise2: G/G24.wav
LongRing1: G/G27b.wav
LongRing2: G/G28.wav
