Beep: A/ABeepProcessing.wav
Error: A/AError2.wav
Failure: A/AFailure1.wav
Finish: A/AFinished1.wav
Help: A/AHelp.wav
Hey: A/AHey.wav
Proccessing: A/AHmm2.wav
NotUnderstood: A/AHuh2.wav
OK: A/AOK.wav
Wait: A/AOneMomentPlease.wav
Ready: A/AReady.wav
Fault: A/AFault.wav

Attention C2BeepsFast
Attention C2LowBeepsFast
Confirm C3BeepFast
Attention CAttention
Call CBeep2Tone
PayAttention CBeepVary
CallTo CBmmmm
MsgReceived CDeBeep
MsgReceived CFastPulse
Ring CKaching2
Ring CKaching3
HangOn CKachingFailed
RequestReceived CMrnful2
Battery CPlugMeIn1
Battery CPlugMeIn2
Battery CPlugMeIn3
Bell DC01a
Ring D02p
Alarm D04
Alarm D05
Alarm D09
Alarm D17
Alarm D23
Alarm D32
Ouch DOuch
Receive E01
Atention E06
Atention E07
Call E09
Pairing E12
Ring F01
LongRing F06
Attention F09
HighAttention F10
Warning F12
Warning F14
Warning G01
Noise G03
Noise G11
Noise G17
RepetitiveNoise G20
RepetitiveNoise G24
Ring G25
LongRing G27b
LongRing G28
Beep H05
Ring H07
Error I01
Ring IOh2
Recognize IAck1
Attention IAttn1
Attention IAttention1
Warning IBatWarn4
Warning IDiag2
Warning IDiag3
Alert IDiagAlrt1
Error IErrgh1
Success IGotIt
Attention IHey2
Attempt IITried1
Processing IMmm2
Failure ISad1
Attention IWohoo1
Failure JErrgh
Hey JHey2
Hey JHey
Error JHm
Error JOh
Failure JOops2
Failure JOops
Success JWooHoo2
Success JWooHoo
Error KAw
Error KDuh
Attention KHey-A1
Error KOh
Error KUgHa
Error KUgOh-C#3
Attention L02
Attention L05-D#4
Alarm L24-E5
Proccessing MCalculating
Confirm MConfirm
Error MErEr
Error MError
Done MGotIt
Done MIDidIt
Abort MIDontUnderstand
Wait MOneMomentPlease
Wait MOneMoment
Processing MProcessing
Abort MSorry
Wait MStandBy
Success MSuccess
Done MTaskCompleted
Processing MThinking
Wait MWaiting
Error MWeHaveAProblem
Done MYouGotIt
