Beep: A/ABeepProcessing.wav
Error: A/AError2.wav
Failure: A/AFailure1.wav
Finish: A/AFinished1.wav
Help: A/AHelp.wav
Hey: A/AHey.wav
Proccessing: A/AHmm2.wav
NotUnderstood: A/AHuh2.wav
OK: A/AOK.wav
Wait: A/AOneMomentPlease.wav
Ready: A/AReady.wav
Fault: A/AFault.wav
