#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on 2017.09.25

@author: Patrick Nagel
"""

import sys

import rospy
import actionlib

from mdr_ask_action.msg import AskAction, AskGoal

def print_usage_info():
    rospy.loginfo("usage: ask <triggering_statement>")
    rospy.loginfo("       where <triggering_statement> is a string")

if __name__ == '__main__':
    rospy.init_node('ask_client_test')
    client = actionlib.SimpleActionClient('ask_server', AskAction)
    client.wait_for_server()

    try:
        goal = AskGoal()
        user_input_triggering_statement = sys.argv[1]
        goal.triggering_statement = user_input_triggering_statement
        timeout = 15.0
        rospy.loginfo("Sending action lib goal to ask_server, triggering statement: "\
                        + goal.triggering_statement)
        client.send_goal(goal)
        client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
        print client.get_result()
    except:
        rospy.logerr("An exception has been thrown")
        print_usage_info()
    