#!/usr/bin/env python
import rospy
import smach

from smach_ros import ActionServerWrapper, IntrospectionServer
from mdr_gender_recognition.skill import GenderRecognitionSkill
from mdr_gender_recognition.msg import GenderRecognitionAction


if __name__ == '__main__':
    rospy.init_node('gender_recognition_server')

    # construct state machine
    sm = GenderRecognitionSkill()

    # smach viewer
    sis = IntrospectionServer('gender_recognition_smach_viewer', sm,
                              '/gender_recognition_SMACH_VIEWER')
    sis.start()

    asw = ActionServerWrapper(
        server_name='gender_recognition_server',
        action_spec=GenderRecognitionAction,
        wrapped_container=sm,
        succeeded_outcomes=['OVERALL_SUCCESS'],
        aborted_outcomes=['OVERALL_FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='gender_recognition_goal',
        feedback_key='gender_recognition_feedback',
        result_key='gender_recognition_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
