#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on 2017.09.23

@author: Patrick Nagel
"""

import rospy
import smach

from smach_ros import ActionServerWrapper, IntrospectionServer
from mdr_answer_action.msg import AnswerAction, AnswerResult, AnswerFeedback
from mdr_answer_action.action_states import InitializeAnswer, InitializationError,\
                                    MatchAnswer, MatchError


class AnswerSkill(smach.StateMachine):

    def __init__(self):
        smach.StateMachine.__init__(self,
                                    outcomes=['OVERALL_SUCCESS', 'OVERALL_FAILED', 'PREEMPTED'],
                                    input_keys=['answer_goal'],
                                    output_keys=['answer_feedback', 'answer_result'])
        with self:
            smach.StateMachine.add('INITIALIZE_ANSWER', InitializeAnswer(),
                                   transitions={'succeeded':'MATCH_ANSWER',
                                                'failed':'INITIALIZATION_ERROR'})
            smach.StateMachine.add('INITIALIZATION_ERROR', InitializationError(),
                                   transitions={'error_detected':'OVERALL_FAILED',
                                                'processing':'INITIALIZATION_ERROR'})
            smach.StateMachine.add('MATCH_ANSWER', MatchAnswer(),
                                   transitions={'succeeded':'OVERALL_SUCCESS',
                                                'answer_not_found':'MATCH_ERROR',
                                                'processing':'MATCH_ANSWER'})
            smach.StateMachine.add('MATCH_ERROR', MatchError(),
                                   transitions={'error_detected':'OVERALL_FAILED',
                                                'processing':'MATCH_ERROR'})


if __name__ == '__main__': 
    rospy.init_node('answer_server')

    # construct state machine
    sm = AnswerSkill()

    # smach viewer
    sis = IntrospectionServer('answer_smach_viewer', sm, '/ANSWER_SMACH_VIEWER')
    sis.start()

    # construct the action server wrapper
    asw = ActionServerWrapper(
        server_name='answer_server',
        action_spec=AnswerAction,
        wrapped_container=sm,
        succeeded_outcomes=['OVERALL_SUCCESS'],
        aborted_outcomes=['OVERALL_FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='answer_goal',
        feedback_key='answer_feedback',
        result_key='answer_result')

    # Run the server in the background thread
    asw.run_server()
    rospy.spin()
