#!/usr/bin/env python
"""
Created on 2023.09.19

@author: Vivek Mannava
@email: vivek.mannava@smail.inf.h-brs.de
"""
import rospy
import actionlib

from mdr_retrieve_info_action.msg import RetrieveInfoAction
from mdr_retrieve_info_action.action_states import RetrieveInfoSM

class RetrieveInfoServer(object):
    def __init__(self):
        self.use_whisper = rospy.get_param('~use_whisper')
        rospy.loginfo('[Retrieve info server] Initialising state machine')
        self.action_sm = RetrieveInfoSM(use_whisper = self.use_whisper)
        rospy.loginfo('[Retrieve info server] State machine initialised')

        self.action_server = actionlib.SimpleActionServer('retrieve_info_server',RetrieveInfoAction,self.execute, False)
        self.action_server.start()
        rospy.loginfo('retrieve info action server ready')

    def execute(self, goal):
        rospy.loginfo('[listen] Received an action request')
        self.action_sm.goal = goal
        self.action_sm.result = None
        self.action_sm.execution_requested = True
        while not self.action_sm.result:
            rospy.sleep(0.05)
        self.action_server.set_succeeded(self.action_sm.result)


if __name__ == '__main__':
    rospy.init_node('listen_server')
    retrieve_info_server = RetrieveInfoServer()
    try:
        retrieve_info_server.action_sm.run()
        while retrieve_info_server.action_sm.is_running and not rospy.is_shutdown():
            rospy.spin()
    except (KeyboardInterrupt, SystemExit):
        print('{0} interrupted; exiting...'.format(retrieve_info_server.action_sm.name))
