#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on 2023.09.19

@author: Vivek Mannava
@email: vivek.mannava@smail.inf.h-brs.de
"""

import sys

import rospy
import roslib
import actionlib

from mdr_retrieve_info_action.msg import RetrieveInfoAction, RetrieveInfoGoal

if __name__ == '__main__':
    rospy.init_node('retrieve_info_client_test')
    client = actionlib.SimpleActionClient('retrieve_info_server', RetrieveInfoAction)
    client.wait_for_server()

    goal = RetrieveInfoGoal()
    try:
        client.send_goal(goal)
        timeout = 10.0
        client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
        rospy.loginfo(client.get_result())

    except Exception as ex:
        rospy.logerr(type(ex).__name__ + ": You have failed!")
