#! /usr/bin/env python
from __future__ import print_function
import rospy
import actionlib

from mdr_handle_open_action.msg import HandleOpenAction, HandleOpenGoal


if __name__ == '__main__':
    rospy.init_node('handle_open_action_client_test')

    client = actionlib.SimpleActionClient('/handle_open_server', HandleOpenAction)
    client.wait_for_server()

    goal = HandleOpenGoal()

    goal.handle_pose.header.frame_id = 'base_link'
    goal.handle_pose.header.stamp = rospy.Time.now()

    goal.handle_pose.pose.position.x = 1.000
    goal.handle_pose.pose.position.y = 0.078
    goal.handle_pose.pose.position.z = 0.400

    goal.handle_pose.pose.orientation.x = 0.000
    goal.handle_pose.pose.orientation.y = 0.000
    goal.handle_pose.pose.orientation.z = 0.000
    goal.handle_pose.pose.orientation.w = 1.000

    timeout = 15.0
    rospy.loginfo('Sending action lib goal to handle_open_server')
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
    print(client.get_result())
