#!/usr/bin/env python
import rospy

from mdr_head_controller.head_controller import HeadController

if __name__ == '__main__':
    rospy.init_node('mdr_head_controller')
    try:
        head = HeadController()
        head.look_up()
        head.look_down()
        head.tilt(0.5)
        head.pan(0.5)
        head.reset()
    except rospy.ROSInterruptException:
        pass
