#!/usr/bin/env python
import rospy

from mdr_command_robot.spoken_joypad_base import SpokenJoypadBase

if __name__ == '__main__':
    rospy.init_node('mdr_spoken_joypad')
    try:
        SpokenJoypadBase()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
